### ISSUE TITLE
No data anymore

### ISSUE THREAD

**Issue by Roelofk85** [heyajohnny/afvalinfo#115]
Hello,

I don't get the data anymore.
Changed nothing, all the sensors say "onbekend".

Config:
```
  - platform: afvalinfo
    resources:
      - restafval
      - papier
      - gft
      - trash_type_today
      - trash_type_tomorrow
    location: terschelling
    postcode: mycode
    streetnumber: 1
    locale: 'nl'
    timespanindays: 14
```

Am i doing something wrong?

Thanks!

Roelof

**Comment by heyajohnny** [comment]
There was a 'gft' bug in the Omrin part, but you should've at least see data for 'restafval' and 'papier'.
I used the postcode 8891gh and streetnumber 1 and it worked as expected (except for the 'gft' bug that is fixed now).
I hope that the fix I just pushed, also fixes your issue. Please let me know if it works again.

**Comment by Dorzel107** [comment]
hello Johnny,

first off all thanks for this component.

for me it didn't fix, here is my config:

```- platform: afvalinfo
  resources:
    - restafval
    - gft
    - papier
    - textiel
    - trash_type_today
  location: 'heerenveen'
  postcode: '8495KG'
  streetnumber: '51'
  locale: 'nl'
```
and this is my log within a few minutes after restart:
```Logger: custom_components.afvalinfo.const.const
Source: custom_components/afvalinfo/location/omrin.py:193
Integration: afvalinfo (documentation)
First occurred: 9:17:17 (1 occurrences)
Last logged: 9:17:17

2020-09-03
```
and another one:
```Logger: custom_components.afvalinfo.const.const
Source: custom_components/afvalinfo/location/omrin.py:58
Integration: afvalinfo (documentation)
First occurred: 9:17:17 (5 occurrences)
Last logged: 9:17:17

Something went wrong while splitting data: UnboundLocalError("local variable 'dataFilteredByType' referenced before assignment"). This probably means that trash type 'gft' is not supported on your location
Something went wrong while splitting data: UnboundLocalError("local variable 'dataFilteredByType' referenced before assignment"). This probably means that trash type 'papier' is not supported on your location
````
gft is the only sensor whitout sensor data

**Comment by heyajohnny** [comment]
@Dorzel107 I've pushed another fix. Please let me know if it works

**Comment by Dorzel107** [comment]
Johnny,

great work  🥇 

the gft sensor is now populated, so it works. altough the logbook warnings persist.

**Comment by Roelofk85** [comment]
No, it's still not working...

**Comment by heyajohnny** [comment]
@Roelofk85 Can you please send me a postcode and streetnumber that isn't working. The one's that I've tried are working just fine, so I can't reproduce the issue.

**Comment by Roelofk85** [comment]
It's working! Mixed up my postal code numbers with my old house! 

Tnx 👍👍😃

**Comment by Roelofk85** [comment]
Fixed

**Comment by heyajohnny** [comment]
No problem! Good to hear it's working again :)
